version: 0.2


phases:
  install:
    commands:
      - sudo su
      - yum update -y
      - yum install httpd -y
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - sudo yum -y install curl
      - curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
      - sudo yum install -y nodejs
      - sudo yum -y install gcc-c++ make
      - curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
      - sudo yum -y install yarn
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - cd /var/www/html
      - rm -rf index.html
      - sudo yum -y install httpd 
      - sudo yum install git -y
      - git init
  pre_build:
    commands:
      - npm i @vue/cli-service --legacy-peer-deps
      
  build:
    commands:
      - npm install --legacy-peer-deps
      - screen -d -m npx quasar dev
  post_build:
    commands:
      - aws s3 sync dist $S3_BUCKET
