version: 0.2

phases:
  install:
    commands:
      - sudo su
      - yum update -y
      - yum install httpd -y
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - nvm install 16
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - cd /var/www/html
      - rm -rf index.html
      - systemctl start httpd
      - systemctl enable httpd
      - sudo yum install git -y
      - git init
  pre_build:
    commands:
      - npm install --legacy-peer-deps
      - npm i @vue/cli-service --legacy-peer-deps
      
  build:
    commands:
      - screen -d -m npx quasar dev
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET
